name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 530303603554
  ECR_REGISTRY: 530303603554.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
            --region $AWS_REGION | \
            docker login \
            --username AWS \
            --password-stdin \
            $ECR_REGISTRY

      - name: Verify ECR Repositories
        run: |
          aws ecr describe-repositories \
            --repository-names \
              order-service \
              payment-service \
              inventory-service \
            --region $AWS_REGION

      # -----------------------------
      # Order Service
      # -----------------------------

      - name: Build Order Service
        run: |
          docker build \
            -t $ECR_REGISTRY/order-service:${{ github.sha }} \
            -t $ECR_REGISTRY/order-service:latest \
            ./order-service

      - name: Push Order Service
        run: |
          docker push $ECR_REGISTRY/order-service:${{ github.sha }}
          docker push $ECR_REGISTRY/order-service:latest

      # -----------------------------
      # Payment Service
      # -----------------------------

      - name: Build Payment Service
        run: |
          docker build \
            -t $ECR_REGISTRY/payment-service:${{ github.sha }} \
            -t $ECR_REGISTRY/payment-service:latest \
            ./payment-service

      - name: Push Payment Service
        run: |
          docker push $ECR_REGISTRY/payment-service:${{ github.sha }}
          docker push $ECR_REGISTRY/payment-service:latest

      # -----------------------------
      # Inventory Service
      # -----------------------------

      - name: Build Inventory Service
        run: |
          docker build \
            -t $ECR_REGISTRY/inventory-service:${{ github.sha }} \
            -t $ECR_REGISTRY/inventory-service:latest \
            ./inventory-service

      - name: Push Inventory Service
        run: |
          docker push $ECR_REGISTRY/inventory-service:${{ github.sha }}
          docker push $ECR_REGISTRY/inventory-service:latest