name: Debug AWS GitHub OIDC

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:

  debug-oidc:

    runs-on: ubuntu-latest

    steps:

      - name: Show GitHub Context
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Ref        : ${{ github.ref }}"
          echo "Branch     : ${{ github.ref_name }}"
          echo "Event      : ${{ github.event_name }}"
          echo "Actor      : ${{ github.actor }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity