```yaml
name: AWS OIDC Debug

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug GitHub OIDC Token
        uses: github/actions-oidc-debugger@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
```
